name: CI
on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Scala Environment
      uses: olafurpg/setup-scala@v10
    - name: Run tests
      working-directory: ./backend
      run: sbt test
