name: CD
on:
  push:
    branches: [ master ]
jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Scala Environment
      uses: olafurpg/setup-scala@v10
    - name: Tests
      working-directory: ./backend
      run: sbt test
    - name: Assembly app
      working-directory: ./backend
      run: sbt assembly
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        dockerfile: ./backend/Dockerfile
        buildArgs: TARGET_FOLDER=./backend/target
        image: neftales/converter-api
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
