name: Converter
on:
  push:
    branches: [ setup-actions ]
jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: olafurpg/setup-scala@v10
    - name: Enter in backend folder
      run: cd backend
    - name: Tests
      run: sbt test
    - name: package
      run: sbt assembly
